FROM php:7.4.12-apache

RUN apt-get update

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

RUN chmod -R 774 /var/www/html/

RUN chown -R www-data. /var/www/html/

COPY patch.php /var/www/html/

EXPOSE 80
